version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/app/
        links:
            - php
        networks:
            - defaultNetwork

    php:
        build:
                context: .
                dockerfile: docker/php/Dockerfile
        volumes:
            - .:/app/
        depends_on:
            - db
        networks:
            - defaultNetwork
    
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - '5432:5432'
        volumes: 
            - ./postgres-data:/var/lib/postgresql/data
            - ./docker/postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        networks:
            - defaultNetwork
volumes:
    postgres-data:
networks:
    defaultNetwork: